[tool.poetry]
name = "pypme"
version = "0.1.0"
description = "Python library for PME (Public Market Equivalent) calculation"
authors = ["ymyke"]
license = "MIT"
repository = "https://github.com/ymyke/pypme"
homepage = "https://github.com/ymyke/pypme"

[tool.poetry.dependencies]
python = "^3.7"
xirr = "^0.1.6"
numpy-financial = "^1.0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipykernel = "^6.9.1"
black = "^22.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
